"""Add abstract_s3_key

Revision ID: 165f0273c245
Revises: 688e7fd7ea55
Create Date: 2026-04-17 10:27:53.387034

"""
from typing import Sequence, Union

from alembic import op
# pyrefly: ignore [missing-import]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165f0273c245'
down_revision: Union[str, Sequence[str], None] = '688e7fd7ea55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'thesis_interview_sessions' not in tables:
        op.create_table('thesis_interview_sessions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('start_time', sa.DateTime(), nullable=False),
            sa.Column('end_time', sa.DateTime(), nullable=True),
            sa.Column('status', sa.String(), nullable=False),
            sa.Column('score_technical', sa.Float(), nullable=True),
            sa.Column('score_problem_solving', sa.Float(), nullable=True),
            sa.Column('score_coding', sa.Float(), nullable=True),
            sa.Column('score_communication', sa.Float(), nullable=True),
            sa.Column('score_soft_skills', sa.Float(), nullable=True),
            sa.Column('total_score', sa.Float(), nullable=True),
            sa.Column('passed', sa.Boolean(), nullable=True),
            sa.Column('feedback_summary', sa.String(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_thesis_interview_sessions_id'), 'thesis_interview_sessions', ['id'], unique=False)
        
    if 'upcoming_student_interview_sessions' not in tables:
        op.create_table('upcoming_student_interview_sessions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('start_time', sa.DateTime(), nullable=False),
            sa.Column('end_time', sa.DateTime(), nullable=True),
            sa.Column('status', sa.String(), nullable=False),
            sa.Column('score_cte_subject_matter', sa.Float(), nullable=True),
            sa.Column('score_cte_teaching', sa.Float(), nullable=True),
            sa.Column('score_cte_communication', sa.Float(), nullable=True),
            sa.Column('score_cte_motivation', sa.Float(), nullable=True),
            sa.Column('score_cte_academic', sa.Float(), nullable=True),
            sa.Column('score_cte_problem_solving', sa.Float(), nullable=True),
            sa.Column('score_cte_leadership', sa.Float(), nullable=True),
            sa.Column('score_cbapa_business', sa.Float(), nullable=True),
            sa.Column('score_cbapa_analytical', sa.Float(), nullable=True),
            sa.Column('score_cbapa_communication', sa.Float(), nullable=True),
            sa.Column('score_cbapa_entrepreneurial', sa.Float(), nullable=True),
            sa.Column('score_cbapa_academic', sa.Float(), nullable=True),
            sa.Column('score_cbapa_leadership', sa.Float(), nullable=True),
            sa.Column('score_cbapa_ethical', sa.Float(), nullable=True),
            sa.Column('score_technical', sa.Float(), nullable=True),
            sa.Column('score_problem_solving', sa.Float(), nullable=True),
            sa.Column('score_coding', sa.Float(), nullable=True),
            sa.Column('score_communication', sa.Float(), nullable=True),
            sa.Column('score_soft_skills', sa.Float(), nullable=True),
            sa.Column('total_score', sa.Float(), nullable=True),
            sa.Column('passed', sa.Boolean(), nullable=True),
            sa.Column('feedback_summary', sa.String(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_upcoming_student_interview_sessions_id'), 'upcoming_student_interview_sessions', ['id'], unique=False)

    if 'thesis_interview_messages' not in tables:
        op.create_table('thesis_interview_messages',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('session_id', sa.Integer(), nullable=False),
            sa.Column('role', sa.String(), nullable=False),
            sa.Column('content', sa.String(), nullable=False),
            sa.Column('timestamp', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['session_id'], ['thesis_interview_sessions.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_thesis_interview_messages_id'), 'thesis_interview_messages', ['id'], unique=False)

    if 'upcoming_student_interview_messages' not in tables:
        op.create_table('upcoming_student_interview_messages',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('session_id', sa.Integer(), nullable=False),
            sa.Column('role', sa.String(), nullable=False),
            sa.Column('content', sa.String(), nullable=False),
            sa.Column('timestamp', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['session_id'], ['upcoming_student_interview_sessions.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_upcoming_student_interview_messages_id'), 'upcoming_student_interview_messages', ['id'], unique=False)

    columns = [col['name'] for col in inspector.get_columns('thesis_interview_sessions')]
    if 'abstract_s3_key' not in columns:
        op.add_column('thesis_interview_sessions', sa.Column('abstract_s3_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thesis_interview_sessions', 'abstract_s3_key')
    # ### end Alembic commands ###
