"""Add abstract_s3_key

Revision ID: 165f0273c245
Revises: 688e7fd7ea55
Create Date: 2026-04-17 10:27:53.387034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165f0273c245'
down_revision: Union[str, Sequence[str], None] = '688e7fd7ea55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thesis_interview_sessions', sa.Column('abstract_s3_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thesis_interview_sessions', 'abstract_s3_key')
    # ### end Alembic commands ###
