"""Add personal details and department to user

Revision ID: 6468797a3a4a
Revises: 256585ea09f6
Create Date: 2026-03-25 14:23:03.950937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6468797a3a4a'
down_revision: Union[str, Sequence[str], None] = '256585ea09f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('middlename', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('department', sa.String(), server_default='CCIT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'middlename')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
