"""Add CTE scoring criteria

Revision ID: 8f86f580a88c
Revises: 5c0dcb963c7b
Create Date: 2026-03-27 16:55:19.762534

"""
from typing import Sequence, Union

from alembic import op
# pyrefly: ignore [missing-import]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f86f580a88c'
down_revision: Union[str, Sequence[str], None] = '5c0dcb963c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'interview_sessions' not in inspector.get_table_names():
        op.create_table('interview_sessions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('start_time', sa.DateTime(), nullable=False),
            sa.Column('end_time', sa.DateTime(), nullable=True),
            sa.Column('status', sa.String(), nullable=False),
            sa.Column('score_technical', sa.Float(), nullable=True),
            sa.Column('score_problem_solving', sa.Float(), nullable=True),
            sa.Column('score_coding', sa.Float(), nullable=True),
            sa.Column('score_communication', sa.Float(), nullable=True),
            sa.Column('score_soft_skills', sa.Float(), nullable=True),
            sa.Column('total_score', sa.Float(), nullable=True),
            sa.Column('passed', sa.Boolean(), nullable=True),
            sa.Column('feedback_summary', sa.String(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_interview_sessions_id'), 'interview_sessions', ['id'], unique=False)

    op.add_column('interview_sessions', sa.Column('score_cte_subject_matter', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cte_teaching', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cte_communication', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cte_motivation', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cte_academic', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cte_problem_solving', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cte_leadership', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'score_cte_leadership')
    op.drop_column('interview_sessions', 'score_cte_problem_solving')
    op.drop_column('interview_sessions', 'score_cte_academic')
    op.drop_column('interview_sessions', 'score_cte_motivation')
    op.drop_column('interview_sessions', 'score_cte_communication')
    op.drop_column('interview_sessions', 'score_cte_teaching')
    op.drop_column('interview_sessions', 'score_cte_subject_matter')
    # ### end Alembic commands ###
