"""Add CTE scoring criteria

Revision ID: 8f86f580a88c
Revises: 5c0dcb963c7b
Create Date: 2026-03-27 16:55:19.762534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f86f580a88c'
down_revision: Union[str, Sequence[str], None] = '5c0dcb963c7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('score_cte_subject_matter', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cte_teaching', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cte_communication', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cte_motivation', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cte_academic', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cte_problem_solving', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cte_leadership', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'score_cte_leadership')
    op.drop_column('interview_sessions', 'score_cte_problem_solving')
    op.drop_column('interview_sessions', 'score_cte_academic')
    op.drop_column('interview_sessions', 'score_cte_motivation')
    op.drop_column('interview_sessions', 'score_cte_communication')
    op.drop_column('interview_sessions', 'score_cte_teaching')
    op.drop_column('interview_sessions', 'score_cte_subject_matter')
    # ### end Alembic commands ###
