"""Add CBAPA scoring criteria

Revision ID: 2485f02507c1
Revises: 8f86f580a88c
Create Date: 2026-03-27 17:05:06.863590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2485f02507c1'
down_revision: Union[str, Sequence[str], None] = '8f86f580a88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('score_cbapa_business', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cbapa_analytical', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cbapa_communication', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cbapa_entrepreneurial', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cbapa_academic', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cbapa_leadership', sa.Float(), nullable=True))
    op.add_column('interview_sessions', sa.Column('score_cbapa_ethical', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'score_cbapa_ethical')
    op.drop_column('interview_sessions', 'score_cbapa_leadership')
    op.drop_column('interview_sessions', 'score_cbapa_academic')
    op.drop_column('interview_sessions', 'score_cbapa_entrepreneurial')
    op.drop_column('interview_sessions', 'score_cbapa_communication')
    op.drop_column('interview_sessions', 'score_cbapa_analytical')
    op.drop_column('interview_sessions', 'score_cbapa_business')
    # ### end Alembic commands ###
