/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 professor.glb 
Author: Kanna-Nakajima (https://sketchfab.com/Kanna-nakajima)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mococo-abyssgard-86ee8396d2b543a1950c83f73707cb6e
Title: Mococo Abyssgard
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/professor.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.pCube31_accessories_0.geometry} material={materials.accessories} />
        <mesh geometry={nodes.pCube31_Hair_0.geometry} material={materials.Hair} />
        <mesh geometry={nodes.pCube31_Common_acc_0.geometry} material={materials.Common_acc} />
        <mesh geometry={nodes.pCube31_jacket_0.geometry} material={materials.jacket} />
        <mesh geometry={nodes.pCube31_inner_0.geometry} material={materials.inner} />
        <mesh geometry={nodes.pCube31_Shoes_0.geometry} material={materials.Shoes} />
        <mesh geometry={nodes.pCube31_Skin_0.geometry} material={materials.Skin} />
      </group>
    </group>
  )
}

useGLTF.preload('/professor.glb')
