name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-1 # Change if your ECR repo is in another region
  ECR_REPOSITORY: fastapi-backend # Replace with your ECR repository name
  AWS_S3_ABSTRACTS_BUCKET_NAME: career-edge-ai-abstracts-610628048969

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      working-directory: ./backend
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        AWS_REGION: ${{ env.AWS_REGION }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: ECR_REGISTRY,ECR_REPOSITORY,AWS_REGION,AWS_S3_ABSTRACTS_BUCKET_NAME
        script: |
          set -e # Ensure the pipeline fails if any command fails!
          
          # Login to ECR on the EC2 instance
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
          
          # Stop and remove ALL existing containers securely
          docker ps -aq | xargs -r docker rm -f
          
          # Deep clean the Docker environment to free up disk space so pulling the new image doesn't fail!
          docker system prune -af --volumes
          
          # Pull the latest image
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
          # Run the new container
          docker run -d \
            --name backend-api-prod \
            -p 80:8000 \
            --restart always \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e AWS_REGION="${{ env.AWS_REGION }}" \
            -e AWS_S3_BUCKET_NAME="${{ secrets.AWS_S3_BUCKET_NAME }}" \
            -e AWS_S3_ABSTRACTS_BUCKET_NAME="${{ env.AWS_S3_ABSTRACTS_BUCKET_NAME }}" \
            -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
            -e GOOGLE_CREDENTIALS_JSON='${{ secrets.GOOGLE_CREDENTIALS_JSON }}' \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest
